apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-platform-controller
  namespace: multi-platform-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-platform-controller
  template:
    metadata:
      labels:
        app: multi-platform-controller
    spec:
      containers:
        - name: multi-platform-controller
          image: multi-platform-controller
          ports:
            - containerPort: 8080
              name: http-metrics
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: Always
          args:
            - "--v=4"
            - "--zap-log-level=4"
            - "--zap-devel=true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: multi-platform-controller
