apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: multi-platform-controller
resources:
  - ./rbac
  - namespace.yaml
  - deployment.yaml
  - provision-shared-host.yaml
  - provision-host-windows.yaml
  - clean-shared-host.yaml
  - openshift-specific-rbac.yaml
  - update-host.yaml
  - metrics_service.yaml
  - provision-host-macos.yaml
configMapGenerator:
  - name: provision-shared-host-script
    namespace: multi-platform-controller
    files:
      - provision-shared-host.sh
  - name: provision-macos-host-script
    namespace: multi-platform-controller
    files:
      - provision-host-macos.sh
  - name: provision-windows-host-script
    namespace: multi-platform-controller
    files:
      - provision-host-windows.sh
  - name: clean-shared-host-script
    namespace: multi-platform-controller
    files:
      - clean-shared-host.sh
  - name: update-host-script
    namespace: multi-platform-controller
    files:
      - update-host.sh
patches:
  - target:
      kind: ClusterRole
      name: multi-platform-controller
    patch: |-
      - op: add
        path: "/metadata/labels"
        value: {"rbac.authorization.k8s.io/aggregate-to-edit": "true"}
  - target:
      name: multi-platform-controller
      kind: Deployment
    path: manager_metrics_patch.yaml
configurations:
- kustomize-config.yaml
